import Head from "next/head";
import Link from "next/link";

import api from "../../api";

const Blog = ({ teste }) => {
  console.log(teste);
  return (
    <div>
      <Head>
        <title>Create Blasdasdasdog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      blog
      <Link href="/" passHref>
        <a>sad</a>
      </Link>
      {teste.map((item, k) => (
        <>
          <Link href={`/blog/${item.id}`}>
            <a>
              <h2>{item.title}</h2>
            </a>
          </Link>
          <hr />
        </>
      ))}
    </div>
  );
};

export const getStaticProps = async () => {
  const teste = await api.getPosts();
  return {
    props: {
      teste,
    },
    revalidate: 7200,
  };
};

export default Blog;
