import Head from "next/head";
import styles from "../styles/Home.module.css";
import Script from "next/script";
export default function Home({ name, posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      nome: {name}
      <hr />
      <div className={styles.containerPolitica}>
        <p>
          Ao enviar, você confirma a veracidade das informações prestadas neste
          formulário, bem como autoriza a UNICASA a verificar tais dados. Esteja
          ciente que o preenchimento de formulário não implica em nenhum
          compromisso para ambas as partes, em especial, não os obriga à
          assinatura de qualquer documento ou compromisso, sendo as informações
          aqui fornecidas meramente cadastrais e estritamente comerciais. A
          Unicasa se compromete a tratar seus dados pessoais dispostos no
          formulário em conformidade com a Lei Geral de Proteção de Dados (Lei
          13.709/2018), sendo eliminados de maneira segura após o tempo
          necessário. Para mais informações, consulte nossa Política de
          Privacidade, disponível no site.
        </p>
      </div>
      <div className={styles.btnPolitica}>
        <input type="checkbox" />
        <span>
          Aceito os Termos de Uso e a{" "}
          <a href="/">
            <strong>Política de Privacidade</strong>
          </a>
        </span>
      </div>
      <Script src="adasd" strategy="afterInteractive" />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await res.json();
  return {
    props: {
      posts,
      name: "teste",
    },
  };
};
